name: Print some text every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        type: choice
        options:
          - dev
          - int
          - uat
          - prod
        default: 'dev'
      color:
        description: 'Select the cluster color.'
        required: true
        type: choice
        options:
          - blue
          - green
        default: 'blue'

jobs:
  print_text:
    runs-on: ['ubuntu-20.04']
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'dev' # here is the default message
          DEFAULT_COLOR: 'blue'
        run: |
          echo "MESSAGE=${{ github.event.inputs.text_to_print || env.DEFAULT_MESSAGE }}" >> $GITHUB_ENV
          echo "COLOR=${{ github.event.inputs.color || env.DEFAULT_COLOR }}" >> $GITHUB_ENV
          echo "$RUNNER_GROUP" | sed -r 's/ubuntu-([^-]+)-.*/\1/'
      - name: Print some text
        run: echo Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz
        
