name: Print some text every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        type: choice
        options:
          - dev
          - int
          - uat
        default: 'dev'
      color:
        description: 'Select the cluster color.'
        required: true
        type: choice
        options:
          - blue
          - green
        default: 'blue'
env:
  TIER: Monday

jobs:
  print_text:
    runs-on: ['ubuntu-20.04', "${{ github.event.inputs.text_to_print || github.env.DEFAULT_MESSAGE }}"]
    steps:
      - name: Set the variables
        env:
          DEFAULT_MESSAGE: 'prod' # here is the default message
          DEFAULT_COLOR: 'blue'
        shell: bash
        run: |
          echo "MESSAGE=${{ github.event.inputs.text_to_print || github.env.DEFAULT_MESSAGE }}"
          echo "COLOR=${{ github.event.inputs.color || github.env.DEFAULT_COLOR }}"
          echo $TIER
      - name: Print some text
        run: echo Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz
        
  print_text1:
    runs-on: ['ubuntu-20.04']
    steps:
      - name: Set the variables2
        env:
          DEFAULT_MESSAGE: 'prod2' # here is the default message
          DEFAULT_COLOR: 'blue'
        shell: bash
        run: |
          echo "MESSAGE=${{ github.event.inputs.text_to_print || github.env.DEFAULT_MESSAGE }}"
          echo "COLOR=${{ github.event.inputs.color || env.DEFAULT_COLOR }}" >> $GITHUB_ENV
          echo 2 $TIER
      - name: Print some text
        run: echo Kolkata red error -n kolkata consistent --hyd abc-$MESSAGE-$COLOR-xyz
        
